"""empty message

Revision ID: d2df9ec10690
Revises: 1e080cf3902a
Create Date: 2021-03-28 13:37:23.565305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2df9ec10690'
down_revision = '1e080cf3902a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('item', sa.Column('lastmodified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'lastmodified')
    op.drop_column('item', 'created')
    # ### end Alembic commands ###
